import 'package:flutter/material.dart';

final ThemeData myTheme = ThemeData(
  useMaterial3: true,
  applyElevationOverlayColor: false,
  colorScheme:
      ColorScheme.fromSeed(seedColor: const Color.fromRGBO(0, 121, 107, 1)),
  brightness: Brightness.light,
  scaffoldBackgroundColor: const Color(0xfffafdfb),
  secondaryHeaderColor: const Color(0xffe3f2fd),
  shadowColor: const Color(0xff000000),
  splashColor: const Color(0x66c8c8c8),
  splashFactory: InkSplash.splashFactory,
  canvasColor: const Color(0xfffafdfb),
  cardColor: const Color(0xfffafdfb),
  dialogBackgroundColor: const Color(0xfffafdfb),
  disabledColor: const Color(0x61000000),
  dividerColor: const Color(0x1f191c1b),
  focusColor: const Color(0x1f000000),
  highlightColor: const Color(0x66bcbcbc),
  hintColor: const Color(0x99000000),
  hoverColor: const Color(0x0a000000),
  iconTheme: const IconThemeData(color: Color(0xdd000000)),
  inputDecorationTheme: const InputDecorationTheme(
      filled: false,
      alignLabelWithHint: false,
      floatingLabelAlignment: FloatingLabelAlignment.start,
      floatingLabelBehavior: FloatingLabelBehavior.auto,
      isCollapsed: false,
      isDense: false),
  buttonTheme: const ButtonThemeData(
    height: 36,
    layoutBehavior: ButtonBarLayoutBehavior.padded,
    padding: EdgeInsets.fromLTRB(24, 4, 24, 4),
    colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff006a60),
        onPrimary: Color(0xffffffff),
        secondary: Color(0xff4a635f),
        onSecondary: Color(0xffffffff),
        error: Color(0xffba1a1a),
        onError: Color(0xffffffff),
        background: Color(0xfffafdfb),
        onBackground: Color(0xff191c1b),
        surface: Color(0xfffafdfb),
        onSurface: Color(0xff191c1b)),
  ),
  primaryTextTheme: const TextTheme(
      bodyLarge: TextStyle(
          color: Color(0xffffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.5,
          textBaseline: TextBaseline.alphabetic),
      bodyMedium: TextStyle(
          color: Color(0xffffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 14,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
          textBaseline: TextBaseline.alphabetic),
      bodySmall: TextStyle(
          color: Color(0xb3ffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 12,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.4,
          textBaseline: TextBaseline.alphabetic),
      labelLarge: TextStyle(
          color: Color(0xffffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 1.25,
          textBaseline: TextBaseline.alphabetic),
      labelMedium: TextStyle(
          color: Color(0xffffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 11,
          fontWeight: FontWeight.w400,
          letterSpacing: 1.5,
          textBaseline: TextBaseline.alphabetic),
      labelSmall: TextStyle(
          color: Color(0xffffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 10,
          fontWeight: FontWeight.w400,
          letterSpacing: 1.5,
          textBaseline: TextBaseline.alphabetic),
      titleLarge: TextStyle(
          color: Color(0xffffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 20,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.15,
          textBaseline: TextBaseline.alphabetic),
      titleMedium: TextStyle(
          color: Color(0xffffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.15,
          textBaseline: TextBaseline.alphabetic),
      titleSmall: TextStyle(
          color: Color(0xffffffff),
          decoration: TextDecoration.none,
          fontFamily: "Lato",
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
          textBaseline: TextBaseline.alphabetic)),

  // Define the default `TextTheme`. Use this to specify the default
  // text styling for headlines, titles, bodies of text, and more.
  textTheme: const TextTheme(
    bodyLarge: TextStyle(
        color: Color(0xdd000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 16,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic),
    // the middle text uses "bodyMedium".
    bodyMedium: TextStyle(
        color: Color(0xdd000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 14,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic),
    bodySmall: TextStyle(
        color: Color(0x8a000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 12,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic),
    labelLarge: TextStyle(
        color: Color(0xdd000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic),
    labelMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 11,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic),
    labelSmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 10,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic),
    //           The title uses "titleLarge"
    titleLarge: TextStyle(
        color: Color(0xdd000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 20,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic),
    titleMedium: TextStyle(
        color: Color(0xdd000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic),
    titleSmall: TextStyle(
        color: Color(0xdd000000),
        decoration: TextDecoration.none,
        fontFamily: "Lato",
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic),
  ),
);
