name: DigitalDairy
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.2
  cupertino_icons:
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.2
  firebase_ui_auth: ^1.10.0
  provider:
  firebase_auth:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: false
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 500
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
