name: DigitalDairy
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cloud_firestore: 5.5.0
  cupertino_icons:
  firebase_core: 3.8.0
  firebase_storage: 12.3.6
  firebase_ui_auth: 1.16.0
  provider:
  firebase_auth: 5.3.3
  flutter:
    sdk: flutter
  google_fonts: 6.2.1
  go_router: 14.6.1
  intl: 0.20.1
  collection: 1.19.1
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: false
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 500
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
